# Working with Dates and Times

In [1]:
import pandas as pd

## Review of Python's datetime Module
- A module is a file of Python code.
- The `datetime` module is part of Python's standard library, a collection of built-in features.
- The common alias for the `datetime` module is `dt`.

In [2]:
import datetime as dt

- The `datetime` module exports `date`, `time`, and `datetime` classes for representing dates and datetimes.
- The `date` constructor accepts arguments for year, month, and day.
- The `time` constructor accepts arguments for hours, minutes, and seconds.
- The `datetime` constructor accepts arguments for year, month, day, hour, minute, and second.
- The constructors default to 0 for any missing values.

In [8]:
someday = dt.date(year=2026, month=12, day=26)

In [9]:
type(dt.date(year=2026, month=12, day=26))

datetime.date

In [16]:
someday.day
someday.month
someday.year

2026

In [19]:
time = dt.time(8,30,45)
type(time)

datetime.time

In [22]:
time.hour
time.second
time.minute

30

In [26]:
somedatetime = dt.datetime(2026,12,26,8,30,45)

In [48]:
somedatetime.date()
somedatetime.time()
somedatetime.strftime(format='%Y-%m-%d')
# %m - month
# %M - minute
# %d - day
# %Y - year-2026
# %y - year - 26
# %D - 12/26/26

'2026-12-26'

## The dt Attribute
- The `dt` attribute on a `Series` exposes a `DatetimeProperties` object with attributes/methods for working with datetimes.
- The `DatetimeProperties` object has attributes like `day`, `month`, and `year` to reveal information about each date in the `Series`.

In [52]:
ibm = pd.read_csv('ibm.csv', parse_dates=['Date'])
ibm.head()

        Date  Open  High   Low  Close  Volume
0 1962-01-02  1.48  1.48  1.46   1.46  407940
1 1962-01-03  1.46  1.48  1.46   1.48  305955
2 1962-01-04  1.48  1.48  1.46   1.46  274575
3 1962-01-05  1.46  1.46  1.43   1.43  384405
4 1962-01-08  1.43  1.43  1.39   1.41  572685

In [56]:
ibm.dtypes

Date      datetime64[us]
Open             float64
High             float64
Low              float64
Close            float64
Volume             int64
dtype: object

In [65]:
ibm['Date'].dt.day
ibm['Date'].dt.month
ibm['Date'].dt.year
ibm['Date'].dt.date
ibm['Date'].dt.day_of_week
ibm['Date'].dt.day_of_year

0         2
1         3
2         4
3         5
4         8
         ..
16123    26
16124    27
16125    28
16126    29
16127    30
Name: Date, Length: 16128, dtype: int32

- The `day_name` method returns the written day of the week.

In [66]:
ibm['Date'].dt.day_name()

0          Tuesday
1        Wednesday
2         Thursday
3           Friday
4           Monday
           ...
16123       Monday
16124      Tuesday
16125    Wednesday
16126     Thursday
16127       Friday
Name: Date, Length: 16128, dtype: str

- Attributes like `is_month_end` and `is_quarter_start` return Boolean `Series`.

In [67]:
ibm['Date'].dt.is_month_end

0        False
1        False
2        False
3        False
4        False
         ...
16123    False
16124    False
16125    False
16126    False
16127    False
Name: Date, Length: 16128, dtype: bool

In [71]:
ibm['Date'].dt.is_quarter_start
ibm[ibm['Date'].dt.is_quarter_start]

            Date    Open    High     Low   Close   Volume
189   1962-10-01    0.91    0.91    0.87    0.87  1937715
314   1963-04-01    1.08    1.08    1.08    1.08   713895
377   1963-07-01    1.12    1.12    1.09    1.09  1561155
441   1963-10-01    1.16    1.17    1.15    1.15   674670
565   1964-04-01    1.53    1.53    1.53    1.53   753120
...          ...     ...     ...     ...     ...      ...
15730 2024-07-01  166.30  169.19  166.24  167.89  3321000
15794 2024-10-01  213.39  213.85  208.82  212.15  3548400
15918 2025-04-01  243.39  245.94  238.94  245.66  4412900
15980 2025-07-01  290.97  291.52  286.55  287.66  3272800
16044 2025-10-01  278.66  285.02  278.61  284.92  4381300

[135 rows x 6 columns]

In [69]:
ibm['Date'].dt.is_year_start

0        False
1        False
2        False
3        False
4        False
         ...
16123    False
16124    False
16125    False
16126    False
16127    False
Name: Date, Length: 16128, dtype: bool

In [70]:
ibm['Date'].dt.is_leap_year

0        False
1        False
2        False
3        False
4        False
         ...
16123    False
16124    False
16125    False
16126    False
16127    False
Name: Date, Length: 16128, dtype: bool

## The Timestamp Type
- Pandas has its own `Timestamp` type for modelling a date or datetime.

- The `Timestamp` constructor also accepts `dt.date` and `dt.datetime` objects.
- The `Timestamp` cannot model a time without a day and thus does not accept `dt.time` objects.

- When we convert a column to `datetime64`, each row actually stores a `Timestamp`.

## Extracting Datetime Rows from a DataFrame
- When generating a Boolean `Series` against a `datetime64` column, you can use either strings, `datetime` objects, or `Timestamp` objects.

- We can set a column of `datetime` values as the index.
- The `DataFrame` sill store a `DatetimeIndex` object.

- Use the `iloc` accessor for index position-based extraction.

- Use the `loc` accessor for index label-based extraction.
- The accessor accepts strings, `datetime` objects, or `Timestamp` objects.
- Use list slicing to extract a sequence of dates.
- The `truncate` method is another alternative for extracting a range of dates..

- The second argument to `loc` represents the column(s) to target.

- Pass a shorter string like `"2025"` or `"2025-03"` to `loc` to select all rows within that year or month.

## The DateOffset Object
- A `DateOffset` object adds time to a `Timestamp` to arrive at a new `Timestamp`.
- The `DateOffset` constructor accepts `days`, `weeks`, `months`, `years` parameters, and more.
- We can pass a `DateOffset` object to the `freq` parameter of the `pd.date_range` function.

## The date_range Function
- The `pd.date_range` function generates a `MultiIndex` of values from a start point to an endpoint.
- We can customize the frequency/gap between each `Timestamp` with the `freq` parameter.
- We can also ask it to generate a certain number of values with the `periods` parameter and either a start or end.

- Let's extract all of the rows that fell on a given date each year.

## Specialized Date Offsets
- Pandas nests more specialized date offsets in `pd.tseries.offsets`.
- The offsets represent custom spans of time (month end, quarter end, year begin, etc).
- Use `+` to move time forward into the future.
- Use `-` to move time backward into the past.

## Timedeltas
- A `Timedelta` is a pandas object that represents a duration (an amount of time).
- Subtracting two `Timestamp` objects will yield a `Timedelta` object (this applies to subtracting a `Series` from another `Series`).
- The `Timedelta` constructor accepts parameters for time as well as string descriptions.